export const brandAssets = {
  accountSetup: require("../../assets/brand/account-setup-card.png"),
  examStep: require("../../assets/brand/exam-step.png"),
  feedback: require("../../assets/brand/feedback.png"),
  generatedPlanHero: require("../../assets/brand/generated-plan-hero.png"),
  homeHero: require("../../assets/brand/home-hero.png"),
  launchChecklist: require("../../assets/brand/launch-checklist.png"),
  logoMaster: require("../../assets/brand/logo-master.png"),
  paceStep: require("../../assets/brand/pace-step.png"),
  parentDashboardHero: require("../../assets/brand/parent-dashboard-hero.png"),
  parentEntryCard: require("../../assets/brand/parent-entry-card.png"),
  privacySecurity: require("../../assets/brand/privacy-security.png"),
  profileStep: require("../../assets/brand/profile-step.png"),
  reviewStep: require("../../assets/brand/review-step.png"),
  studentEntryCard: require("../../assets/brand/student-entry-card.png"),
  subjectsStep: require("../../assets/brand/subjects-step.png"),
  supportAdmin: require("../../assets/brand/support-admin.png"),
} as const;
