export const brandAssets = {
  accountSetup: require("../../assets/brand/account-setup-card.png"),
  appIconSource: require("../../assets/brand/app-icon-source.png"),
  confidenceCheck: require("../../assets/brand/confidence-check.png"),
  emptyNoPlan: require("../../assets/brand/empty-state-no-plan.png"),
  emptyNoProgress: require("../../assets/brand/empty-state-no-progress.png"),
  errorApiOffline: require("../../assets/brand/error-api-offline.png"),
  examStep: require("../../assets/brand/exam-step.png"),
  feedback: require("../../assets/brand/feedback.png"),
  generatedPlanHero: require("../../assets/brand/generated-plan-hero.png"),
  homeHero: require("../../assets/brand/home-hero.png"),
  latestProofParent: require("../../assets/brand/latest-proof-parent.png"),
  launchChecklist: require("../../assets/brand/launch-checklist.png"),
  linkedStudents: require("../../assets/brand/linked-students.png"),
  logoMaster: require("../../assets/brand/logo-master.png"),
  missedSession: require("../../assets/brand/missed-session.png"),
  paceStep: require("../../assets/brand/pace-step.png"),
  parentDashboardHero: require("../../assets/brand/parent-dashboard-hero.png"),
  parentEntryCard: require("../../assets/brand/parent-entry-card.png"),
  privacySecurity: require("../../assets/brand/privacy-security.png"),
  profileStep: require("../../assets/brand/profile-step.png"),
  progressMonitoring: require("../../assets/brand/progress-monitoring.png"),
  reminders: require("../../assets/brand/reminders.png"),
  reviewStep: require("../../assets/brand/review-step.png"),
  splashBrand: require("../../assets/brand/splash-brand.png"),
  studentEntryCard: require("../../assets/brand/student-entry-card.png"),
  studyFocusQueue: require("../../assets/brand/study-focus-queue.png"),
  studyProof: require("../../assets/brand/study-proof.png"),
  subjectsStep: require("../../assets/brand/subjects-step.png"),
  successPlanGenerated: require("../../assets/brand/success-plan-generated.png"),
  successSessionDone: require("../../assets/brand/success-session-done.png"),
  supportAdmin: require("../../assets/brand/support-admin.png"),
  todayTimetable: require("../../assets/brand/today-timetable.png"),
  weeklyReview: require("../../assets/brand/weekly-review.png")
} as const;

