export const brandAssets = {
  accountSetup: require("../../assets/stock/planner-desk.jpg"),
  examStep: require("../../assets/stock/planner-desk.jpg"),
  feedback: require("../../assets/brand/feedback.png"),
  generatedPlanHero: require("../../assets/stock/planner-desk.jpg"),
  homeHero: require("../../assets/stock/home-hero-study-desk.jpg"),
  launchChecklist: require("../../assets/brand/launch-checklist.png"),
  logoMaster: require("../../assets/brand/logo-master.png"),
  paceStep: require("../../assets/stock/calm-study-space.jpg"),
  parentDashboardHero: require("../../assets/stock/parent-study-support.jpg"),
  parentEntryCard: require("../../assets/stock/parent-study-support.jpg"),
  privacySecurity: require("../../assets/brand/privacy-security.png"),
  profileStep: require("../../assets/stock/student-study-focus.jpg"),
  reviewStep: require("../../assets/stock/planner-desk.jpg"),
  studentEntryCard: require("../../assets/stock/student-study-focus.jpg"),
  subjectsStep: require("../../assets/stock/home-hero-study-desk.jpg"),
  supportAdmin: require("../../assets/brand/support-admin.png"),
} as const;
